- Makefile
- census.mk
Don't merge this until the S3 branch has been merged (I branched off of that since it sounds like we're going that way), but this is a basic setup for using years in the Makefile. The only thing I didn't really touch was how to incorporate the columns with year suffixes (i.e. `evictions-2010`) because it sounds like we might be changing that setup anyway
> Support for multiple years of data

- .travis.yml
- Dockerfile
- Makefile
- README.md
Looks like Travis will come in handy for at least scheduling the Batch job after all. Added the Dockerfile now deployed as a container in our AWS account, modified the deployment in Travis to just schedule that, and made the `deploy` command actually upload files to S3. 
Not 100% sure everything works yet, but worst case scenario it won't change any files
> Add AWS Batch Dockerfile and job

- Makefile
- README.md
Fixes #8. Also a dependency for https://github.com/EvictionLab/eviction-maps/issues/54
> Pulling from S3 Excel instead of Google Sheets

- Makefile
Progress on #11. Still need to work on reducing the overall tile size and splitting out those parameters between layers, but for the full country demo I wanted to fix the random missing chunks in tracts and block groups. `--no-tiny-polygon-reduction` was the parameter I had been looking for there
> Update tippecanoe options

- .gitignore
- Dockerfile
- Makefile
- scripts/create_search_index.py
This splits the search JSON file into files for by first one or two characters in the search name. It's potentially a way of faking a search index
> Create static search index, update docker image

- scripts/create_search_index.py
- scripts/group_census_data.py
Corrects some issues with how search data was joined and created overall
> Fix search data generation

- .gitignore
- Dockerfile
- Makefile
- README.md
- col_map.json
- fake.mk
- scripts/create_fake_data.py
- scripts/create_search_index.py
- scripts/group_census_data.py
- search.mk
Closes #21 and is progress on #11. Speeds up the group census data script, allows for the creation of fake data, and modifies the way tiles are created
> Significant refactoring

- scripts/group_census_data.py
> Use -1.0 as NA value

- README.md
- scripts/create_fake_data.py
`make all` is redundant, and there's an inconsistency in using the integer percentage vs float values, so updating that to match current prototypes
> Update random sample data, make commands

- .env.sample
- .gitignore
- Makefile
- README.md
- col_map.json
- demographics.mk
- fake.mk
- requirements.txt
- scripts/create_fake_data.py
- scripts/csvjoin.py
- scripts/demographic_data.py
- scripts/join_90_block_groups.py
Adds census demographics to the build process and deploys them to S3 to be merged to eviction data. Currently not working for block groups though.
> Build census demographics

- demographics.mk
- scripts/demographic_data.py
Closes #38. Won't have eviction data for all of these, but just pulling the context data in case it's used
> Add MSA data to pipeline

- Makefile
> Update tile parameters for block groups

- scripts/convert_00_geo.py
- scripts/demographic_data.py
Fixes #50, but leaves county names alone
> Fix names for cities, tracts, block groups

- demographics.mk
- scripts/census_data.py
- scripts/crosswalk_geo.py
Closes #55. Still need to handle census places, but this fixes counties and their sub-areas.
> Handle changed counties, update sub features

- Makefile
- scripts/create_city_ranking_data.py
> Add build for city rankings

- conf/changed_census_places.csv
- scripts/demographic_data.py
> Shorten cities, remove leftover PR

- scripts/create_public_data.py
> Replace -1 with nan in public data

- Makefile
- scripts/create_counties_search.py
Necessary now that we're switching to Mapbox geocoding which doesn't include counties
> Add county search data to pipeline

- Makefile
- scripts/create_us_average.py
> Create US average eviction data

- scripts/create_data_rankings.py
Closes #76, statically setting `max_year` for now
> Add area-type to city rankings

- Dockerfile
- README.md
- scripts/requirements.txt
> Lock versions in Dockerfile, requirements.txt

- scripts/convert_varnames.py
Skips the identifier and GEOID length check on national data, because it has no ID field.
> skip assertions on national data

- conf/changes/2018-09-19_places_impacted.csv
- scripts/validation/report_missing_eviction_recs.py
Changes:
- Drop the missing record column from the missing data report
- Add a state column with the state abbreviation
- Add updated csv listing impacted places sorted by state
> update missing data report 

- Makefile
- scripts/convert_00_geo.py
> use correct name for county for crosswalk county changes
